#!/usr/bin/env python

import argparse
import numpy
import sys

from prepord import *
from read_spec import *

ap = argparse.ArgumentParser()
ap.add_argument("filelist", metavar="file", nargs="+")
ap.add_argument("-o", type=int)
args = ap.parse_args()

# New read_spec structure.
rs = read_spec()

if args.o is not None:
  rs.overrideorder = args.o

for filename in args.filelist:
  mbjd, wave, flux, e_flux, msk, blaze, vbcv, vrad = rs.read_spec(filename)

  thiswave, thisflux, thise_flux = prepord(rs.singleorder, wave, flux, e_flux, msk)

  npix = len(thiswave)
  
  ww = thise_flux > 0
  snr = thisflux[ww] / thise_flux[ww]
  medsnr = numpy.median(snr)

  print filename, medsnr, "pix"

